name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Modify this to match your branch name
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use a Node.js version that supports your Angular app

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build
        run: ng build --configuration production --base-href="/Victims07102023War/"  # Replace 'repository' with your repository name

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/your-angular-app-folder  # Replace 'your-angular-app-folder' with the actual folder name
          publish_branch: gh-pages
          user_name: GitHub Actions
          user_email: actions@users.noreply.github.com
