name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # Set the Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install bs4
          # Install dependencies using 'python -m pip' command
          
      - name: Setting Index.html after build
        run: |
          wget https://cdn.jsdelivr.net/gh/yanivdg/Victims07102023War@main/Python/githubrootset.py -O githubrootset.py
          python githubrootset.py # Run the downloaded script
          
      - name: Build Angular app
        run: ng build --configuration production --base-href="/Victims07102023War/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/Victim07102023War/
          publish_branch: gh-pages
          user_name: GitHub Actions
          user_email: actions@users.noreply.github.com
