name: Python Service Workflow

on:
  schedule:
      - cron: '0 0 * * *'  # Runs once a day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      python:
        image: python:3.12  # You can change the version as needed
        ports:
          - 8000:8000  # Expose port for your service
        options: --name python-service  # Give a name to your service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # Set the Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install bs4 playwright requests flask gunicorn
          # Install dependencies using 'python -m pip' command

      - name: Run Python Service
        run: |
          wget https://cdn.jsdelivr.net/gh/yanivdg/Victims07102023War@main/Python/scrab.py -O scrab.py
          python scrab.py --mode console  # Run the downloaded script
          
      - name: push kidnapped.html
        run: |

          # Move the file to the desired folder
          mkdir -p main/Python
          mv kidnapped.html main/Python/
          git config --global user.name 'yanivdg'
          git config --global user.email 'yaniv.dg.work@gmail.com'
          # Perform actions if changes are present, such as git add, commit, and push.
          git add kidnapped.html
          git commit -m "updating kiddnapped.html page list"
          git push origin main
